//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Issue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales_Issue()
        {
            this.Sales_Issue_Details = new HashSet<Sales_Issue_Details>();
        }
    
        public int Issued_ID { get; set; }
        public string Emp_ID { get; set; }
        public string Comments { get; set; }
        public string Placement { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public string Modify_By { get; set; }
        public string Created_By { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Issue_Details> Sales_Issue_Details { get; set; }
    }
}
