//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Issue_Details
    {
        public string Inventory_No { get; set; }
        public int Issued_ID { get; set; }
        public int SerialNo { get; set; }
        public string Description { get; set; }
        public string Issued_From { get; set; }
        public string Issued_By { get; set; }
        public string Issue_Type { get; set; }
        public Nullable<System.DateTime> Issued_Date { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public string Modify_By { get; set; }
        public string Status { get; set; }
    
        public virtual Inventory_Available Inventory_Available { get; set; }
        public virtual Sales_Issue Sales_Issue { get; set; }
    }
}
