//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SalesDetails
    {
        public string Name { get; set; }
        public string Sales_IssueComments { get; set; }
        public string Placement { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Sales_IssueStatus { get; set; }
        public string Inventory_No { get; set; }
        public string Issued_From { get; set; }
        public string Issued_By { get; set; }
        public string Issue_Type { get; set; }
        public Nullable<System.DateTime> Issued_Date { get; set; }
        public string SalesDetailsStatus { get; set; }
        public string CatName { get; set; }
        public string Model_Name { get; set; }
        public int Issued_ID { get; set; }
        public string DeptName { get; set; }
        public int SerialNo { get; set; }
        public string Sales_Issue_DetailsComments { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
        public string Modify_By { get; set; }
        public string Description { get; set; }
        public string Designation_Title { get; set; }
        public Nullable<int> Designation_ID { get; set; }
        public string Emp_ID { get; set; }
    }
}
